use bevy::prelude::{Image, Rect, Vec2};

#[derive(Debug, Clone, Copy)]
pub struct AtlasRegion {
    pub path: &'static str,
    pub left: f32,
    pub right: f32,
    pub top: f32,
    pub bottom: f32,
    pub width: f32,
    pub height: f32,
    pub tiles_horizontally: bool,
    pub tiles_vertically: bool,
    pub nine_slice_edge: Option<f32>,
}

impl AtlasRegion {
    pub fn rect_pixels(&self, image: &Image) -> Rect {
        let width = image.width() as f32;
        let height = image.height() as f32;
        Rect {
            min: Vec2::new(self.left * width, self.top * height),
            max: Vec2::new(self.right * width, self.bottom * height),
        }
    }
}

pub fn nine_slice_margins(name: &str) -> Option<[f32; 4]> {
    match name.to_ascii_lowercase().as_str() {
        "glues-characterselect-card-all-bg" => Some([14.0, 11.0, 14.0, 17.0]),
        _ => get_region(name)
            .and_then(|region| region.nine_slice_edge)
            .map(|edge| [edge, edge, edge, edge]),
    }
}

pub fn get_region(name: &str) -> Option<AtlasRegion> {
    match name.to_ascii_lowercase().as_str() {
        "128-redbutton-up" => Some(AtlasRegion {
            path: "data/ui/128BrownButton9Sliced.ktx2",
            left: 0.001953,
            right: 0.919922,
            top: 0.509766,
            bottom: 0.759766,
            width: 470.0,
            height: 128.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(16.0),
        }),
        "128-redbutton-pressed" => Some(AtlasRegion {
            path: "data/ui/128BrownButton9Sliced.ktx2",
            left: 0.001953,
            right: 0.919922,
            top: 0.255859,
            bottom: 0.505859,
            width: 470.0,
            height: 128.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(16.0),
        }),
        "128-redbutton-disable" => Some(AtlasRegion {
            path: "data/ui/128BrownButton9Sliced.ktx2",
            left: 0.001953,
            right: 0.919922,
            top: 0.001953,
            bottom: 0.251953,
            width: 470.0,
            height: 128.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(16.0),
        }),
        "128-redbutton-highlight" => Some(AtlasRegion {
            path: "data/ui/128BrownButton.ktx2",
            left: 0.001953,
            right: 0.863281,
            top: 0.190918,
            bottom: 0.253418,
            width: 441.0,
            height: 128.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(16.0),
        }),
        "glue-bigbutton-brown-up" => Some(AtlasRegion {
            path: "data/ui/Glues-BigButton-Brown-Up.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 256.0,
            height: 64.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glue-bigbutton-brown-down" => Some(AtlasRegion {
            path: "data/ui/Glues-BigButton-Brown-Down.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 256.0,
            height: 64.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glue-bigbutton-brown-highlight" => Some(AtlasRegion {
            path: "data/ui/Glues-BigButton-Brown-Highlight.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 256.0,
            height: 64.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glue-bigbutton-brown-disable" => Some(AtlasRegion {
            path: "data/ui/Glues-BigButton-Brown-Up.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 256.0,
            height: 64.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "defaultbutton-nineslice-up" => Some(AtlasRegion {
            path: "data/ui/login-button-generated-regular-normal.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 500.0,
            height: 132.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(24.0),
        }),
        "defaultbutton-nineslice-pressed" => Some(AtlasRegion {
            path: "data/ui/login-button-generated-regular-pressed.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 500.0,
            height: 132.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(24.0),
        }),
        "defaultbutton-nineslice-highlight" => Some(AtlasRegion {
            path: "data/ui/login-button-generated-regular-highlight.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 500.0,
            height: 132.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(24.0),
        }),
        "defaultbutton-nineslice-disabled" => Some(AtlasRegion {
            path: "data/ui/login-button-generated-regular-disabled.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 500.0,
            height: 132.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: Some(24.0),
        }),
        "glues-characterselect-card-all-bg" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.932617,
            right: 0.991211,
            top: 0.246094,
            bottom: 0.304688,
            width: 60.0,
            height: 60.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-listrealm-bg" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.659180,
            right: 0.933594,
            top: 0.219727,
            bottom: 0.242188,
            width: 281.0,
            height: 23.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-card-empty" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.622070,
            right: 0.930664,
            top: 0.246094,
            bottom: 0.338867,
            width: 316.0,
            height: 95.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-card-empty-hover" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.000977,
            right: 0.309570,
            top: 0.340820,
            bottom: 0.433594,
            width: 316.0,
            height: 95.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-card-singles" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.000977,
            right: 0.303711,
            top: 0.435547,
            bottom: 0.522461,
            width: 310.0,
            height: 89.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-card-singles-hover" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.305664,
            right: 0.608398,
            top: 0.435547,
            bottom: 0.522461,
            width: 310.0,
            height: 89.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-card-selected" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.340820,
            right: 0.674805,
            top: 0.000977,
            bottom: 0.120117,
            width: 342.0,
            height: 122.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "custom-nameplate-bg" => Some(AtlasRegion {
            path: "data/ui/nameplate-bg.ktx2",
            left: 0.0,
            right: 1.0,
            top: 0.0,
            bottom: 1.0,
            width: 300.0,
            height: 60.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-namebg" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.187500,
            right: 0.376953,
            top: 0.562500,
            bottom: 0.622070,
            width: 194.0,
            height: 61.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-tophud-left-bg" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.378906,
            right: 0.585938,
            top: 0.562500,
            bottom: 0.612305,
            width: 212.0,
            height: 51.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-tophud-middle-bg" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.969727,
            right: 0.999023,
            top: 0.125000,
            bottom: 0.174805,
            width: 30.0,
            height: 51.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-tophud-right-bg" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGlues.BLP",
            left: 0.187500,
            right: 0.394531,
            top: 0.624023,
            bottom: 0.673828,
            width: 212.0,
            height: 51.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-gs-tophud-left" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGluesGrayscale.BLP",
            left: 0.435547,
            right: 0.865234,
            top: 0.089844,
            bottom: 0.173828,
            width: 220.0,
            height: 43.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-gs-tophud-middle" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGluesGrayscale.BLP",
            left: 0.705078,
            right: 0.935547,
            top: 0.441406,
            bottom: 0.525391,
            width: 118.0,
            height: 43.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-gs-tophud-right" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGluesGrayscale.BLP",
            left: 0.001953,
            right: 0.431641,
            top: 0.353516,
            bottom: 0.437500,
            width: 220.0,
            height: 43.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-gs-tophud-left-selected" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGluesGrayscale.BLP",
            left: 0.435547,
            right: 0.865234,
            top: 0.001953,
            bottom: 0.085938,
            width: 220.0,
            height: 43.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-gs-tophud-middle-selected" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGluesGrayscale.BLP",
            left: 0.236328,
            right: 0.466797,
            top: 0.441406,
            bottom: 0.525391,
            width: 118.0,
            height: 43.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "glues-characterselect-gs-tophud-right-selected" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CharacterSelect/UICharacterSelectGluesGrayscale.BLP",
            left: 0.001953,
            right: 0.431641,
            top: 0.265625,
            bottom: 0.349609,
            width: 220.0,
            height: 43.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "common-dropdown-c-button" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/COMMON/CommonDropdown.BLP",
            left: 0.001953,
            right: 0.078125,
            top: 0.804688,
            bottom: 0.957031,
            width: 39.0,
            height: 39.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "common-dropdown-icon-back" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/COMMON/CommonDropdown.BLP",
            left: 0.955078,
            right: 0.988281,
            top: 0.003906,
            bottom: 0.070312,
            width: 17.0,
            height: 17.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "common-dropdown-icon-next" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/COMMON/CommonDropdown.BLP",
            left: 0.605469,
            right: 0.638672,
            top: 0.113281,
            bottom: 0.179688,
            width: 17.0,
            height: 17.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "charactercreate-customize-backbutton" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CHARACTERCREATE/CharacterCreate.BLP",
            left: 0.841309,
            right: 0.878418,
            top: 0.204590,
            bottom: 0.241699,
            width: 38.0,
            height: 38.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "charactercreate-customize-nextbutton" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CHARACTERCREATE/CharacterCreate.BLP",
            left: 0.956543,
            right: 0.993652,
            top: 0.204590,
            bottom: 0.241699,
            width: 38.0,
            height: 38.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "charactercreate-customize-palette" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CHARACTERCREATE/CharacterCreate.BLP",
            left: 0.938965,
            right: 0.979980,
            top: 0.104004,
            bottom: 0.113770,
            width: 42.0,
            height: 10.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "charactercreate-customize-palette-selected" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/GLUES/CHARACTERCREATE/CharacterCreate.BLP",
            left: 0.888184,
            right: 0.937988,
            top: 0.104004,
            bottom: 0.123535,
            width: 51.0,
            height: 20.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "ui-hud-actionbar-iconframe" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP",
            left: 0.707031,
            right: 0.886719,
            top: 0.248047,
            bottom: 0.291992,
            width: 46.0,
            height: 45.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "ui-hud-actionbar-iconframe-addrow" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP",
            left: 0.707031,
            right: 0.906250,
            top: 0.297852,
            bottom: 0.347656,
            width: 51.0,
            height: 51.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "ui-hud-actionbar-iconframe-down" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP",
            left: 0.707031,
            right: 0.886719,
            top: 0.508789,
            bottom: 0.552734,
            width: 46.0,
            height: 45.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "ui-hud-actionbar-iconframe-addrow-down" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP",
            left: 0.707031,
            right: 0.906250,
            top: 0.349609,
            bottom: 0.399414,
            width: 51.0,
            height: 51.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "ui-hud-actionbar-iconframe-mouseover" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP",
            left: 0.707031,
            right: 0.886719,
            top: 0.627930,
            bottom: 0.671875,
            width: 46.0,
            height: 45.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "ui-hud-actionbar-iconframe-border" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP",
            left: 0.707031,
            right: 0.886719,
            top: 0.462891,
            bottom: 0.506836,
            width: 46.0,
            height: 45.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        "ui-hud-actionbar-iconframe-flash" => Some(AtlasRegion {
            path: "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP",
            left: 0.707031,
            right: 0.886719,
            top: 0.554688,
            bottom: 0.598633,
            width: 46.0,
            height: 45.0,
            tiles_horizontally: false,
            tiles_vertically: false,
            nine_slice_edge: None,
        }),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn red_button_up_region_exists() {
        let region = get_region("128-redbutton-up").expect("atlas region");
        assert_eq!(region.path, "data/ui/128BrownButton9Sliced.ktx2");
        assert_eq!(region.width, 470.0);
        assert_eq!(region.height, 128.0);
        assert_eq!(region.nine_slice_edge, Some(16.0));
    }

    #[test]
    fn brown_glue_big_button_region_exists() {
        let region = get_region("glue-bigbutton-brown-up").expect("atlas region");
        assert_eq!(region.path, "data/ui/Glues-BigButton-Brown-Up.ktx2");
        assert_eq!(region.width, 256.0);
        assert_eq!(region.height, 64.0);
        assert_eq!(region.nine_slice_edge, None);
    }

    #[test]
    fn login_generated_regular_region_exists() {
        let region = get_region("defaultbutton-nineslice-up").expect("atlas region");
        assert_eq!(
            region.path,
            "data/ui/login-button-generated-regular-normal.ktx2"
        );
        assert_eq!(region.width, 500.0);
        assert_eq!(region.height, 132.0);
        assert_eq!(region.nine_slice_edge, Some(24.0));
    }

    #[test]
    fn char_select_list_backdrop_has_asymmetric_slice_margins() {
        assert_eq!(
            nine_slice_margins("glues-characterselect-card-all-bg"),
            Some([14.0, 11.0, 14.0, 17.0])
        );
    }

    #[test]
    fn wow_action_bar_regions_exist() {
        let region = get_region("ui-hud-actionbar-iconframe-addrow-down").expect("atlas region");
        assert_eq!(region.path, "/home/osso/Projects/wow/Interface/HUD/UIActionBar.BLP");
        assert_eq!(region.width, 51.0);
        assert_eq!(region.height, 51.0);
    }
}
